"""add_occurrence_days_to_habits

Revision ID: 3a9902290eb4
Revises: 747e160fc6de
Create Date: 2025-08-04 15:18:02.097063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9902290eb4'
down_revision: Union[str, Sequence[str], None] = '747e160fc6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('occurrence_days', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'occurrence_days')
    # ### end Alembic commands ###
