"""Update models to match ERD

Revision ID: 5f5aefc171ae
Revises: 0dc171bd635f
Create Date: 2025-07-17 12:15:40.170247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5aefc171ae'
down_revision: Union[str, Sequence[str], None] = '0dc171bd635f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'check_ins', ['id'])
    op.add_column('goals', sa.Column('start_date', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'goals', ['id'])
    op.create_unique_constraint(None, 'habits', ['id'])
    op.create_unique_constraint(None, 'journal_entries', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'journal_entries', type_='unique')
    op.drop_constraint(None, 'habits', type_='unique')
    op.drop_constraint(None, 'goals', type_='unique')
    op.drop_column('goals', 'start_date')
    op.drop_constraint(None, 'check_ins', type_='unique')
    # ### end Alembic commands ###
