"""Add insights_generated_at column to journal entries

Revision ID: 8b432e3930bb
Revises: a7c03061a4dc
Create Date: 2025-07-29 17:04:17.848793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b432e3930bb'
down_revision: Union[str, Sequence[str], None] = 'a7c03061a4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('insights_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'insights_generated_at')
    # ### end Alembic commands ###
