"""add paused and cancelled to goalstatus enum

Revision ID: a7c03061a4dc
Revises: 1a0dd9506a84
Create Date: 2025-07-24 11:12:23.200056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7c03061a4dc'
down_revision: Union[str, Sequence[str], None] = '1a0dd9506a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new values to the goalstatus enum
    op.execute("ALTER TYPE goalstatus ADD VALUE IF NOT EXISTS 'paused'")
    op.execute("ALTER TYPE goalstatus ADD VALUE IF NOT EXISTS 'cancelled'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', name='goalpriority'), server_default=sa.text("'medium'::goalpriority"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
